# Generated by Django 4.1.3 on 2022-12-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_type',
            },
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_consumption', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dicount_type', models.IntegerField()),
            ],
            options={
                'db_table': 'coupon_type',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('payment', models.IntegerField()),
                ('status', models.IntegerField()),
                ('free_fee', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avgstar', models.IntegerField()),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ForeignKey(db_column='logo', on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.picture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.accounts')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.publisher')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number', models.IntegerField()),
                ('intro', models.CharField(max_length=255)),
                ('avgstar', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.categorytype')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.picture')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.shop')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.product')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.publisher')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.shop')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.coupontype')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.order')),
                ('picture', models.ForeignKey(db_column='picture', on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.picture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.product')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.publisher')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='photo',
            field=models.ForeignKey(blank=True, db_column='photo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.picture'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.accounts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.product')),
            ],
            options={
                'db_table': 'cart',
                'unique_together': {('owner', 'product')},
            },
        ),
    ]
