# Generated by Django 4.1.3 on 2022-12-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ForeignKey(db_column='logo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shaker.picture'),
        ),
    ]
