version: '1.0'
services:
  shaker:
    build: 
      context: ./dockerfiles
      dockerfile: shaker.Dockerfile
    depends_on:
      - db
    ports:
      - "8000:5000"
    volumes:
      - .:/shaker
  
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Shaker8787
    ports:
      - "3306:3306"