version: "1.0"
services:
  shaker:
    build:
      context: .
      dockerfile: Dockerfiles/shaker.Dockerfile
    depends_on:
      - db
    ports:
      - "8000:5000"
    volumes:
      - .:/shaker

  db:
    build:
      context: .
      dockerfile: Dockerfiles/db.Dockerfile
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Shaker8787
    ports:
      - "3306:3306"
